services:

  speech-function-classifier:
    build:
      args:
        SERVICE_PORT: 8108
        SERVICE_NAME: speech_function_classifier # has to be the same with skill dir name
      context: annotators/speech_function_classifier
    command: uvicorn server:app --host 0.0.0.0 --port 8108
    ports:
      - 8108:8108
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 2.5G
        reservations:
          memory: 2.5G

  speech-function-predictor:
    build:
      args:
        SERVICE_PORT: 8107
        SERVICE_NAME: speech_function_predictor # has to be the same with skill dir name
      context: annotators/speech_function_predictor
    command: uvicorn server:app --host 0.0.0.0 --port 8107
    ports:
      - 8107:8107
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 768M
        reservations:
          memory: 768M

  midas-classification:
    build:
      args:
        CONFIG: midas_conv_bert.json
      context: ./annotators/midas_classification
    command: flask run -h 0.0.0.0 -p 8090
    ports:
      - 8090:8090
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - FLASK_APP=server
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 3G

version: '3.7'
